name: Yuriy Shiryaev
description: Finacial graphic designer
meta_description: "I am a graphic designer based in Czech Republic, Prague. The most inspiration I find in meaningful, logical and reasonable design."

markdown: kramdown
highlighter: rouge
logo: true
gems: [jekyll-paginate]
paginate: 15
paginate_path: "page:num"
baseurl: "http://yuriy.eu"
timezone: CZ
domain_name: 'http://yuriy.eu'
paginate: 7
collections: 
 projects:
  output: true

# Details for the RSS feed generator
url:            'http://yuriy.eu'
author:         'Yuriy Shiryaev'
twitter: 'yuriysteam'