name: Yuriy Shiryaev
description: Finacial product designer
meta_description: "Fintech product designer. Improving people’s lives through design. With business in mind."

markdown: kramdown
highlighter: rouge
logo: true 
paginate_path: "page:num"
timezone: CZ
domain_name: 'http://yuriy.eu'
baseurl:
plugins:
  - jekyll-sitemap 
paginate: 7
collections: 
 projects:
  output: true
  trips:
  output: true

# Details for the RSS feed generator
url:            'http://yuriy.eu'
author:         'Yuriy Shiryaev'
twitter: 'yuriysteam'

feed_items: 10
feed_update_period: daily
feed_update_frequency: 1


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/