name: Yuriy Shiryaev
description: "Fintech product designer and manager. I help brands solve tough problems and deliver digital fintech products."

markdown: kramdown
highlighter: rouge
logo: true 
timezone: CZ
domain_name: 'https://yuriy.eu'
baseurl: 
plugins:
  - jekyll-paginate
  - jekyll-sitemap 

paginate: 10
paginate_path: "/blog/page:num/"

collections: 
 projects:
  output: true
# koreaposts:
#  output: true
# cafe:
#  output: true
# loots:
#  output: true
  

# Details for the RSS feed generator
url:            'https://yuriy.eu'
author:         'Yuriy Shiryaev'
twitter: 'yuriysteam'

feed_items: 10
feed_update_period: daily
feed_update_frequency: 1


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/