name: Yuriy Shiryaev
description: Graphic designer
meta_description: "I am a graphic designer from Russia currently living and studying in Prague. Most inspiration I find in meaningful, logical and reasonable things."

markdown: kramdown
highlighter: Rouge
logo: true
gems: [jekyll-paginate]
paginate: 15
paginate_path: "page:num"
baseurl: /
domain_name: 'http://yuriy.eu'
paginate: 7
collections: 
 projects:
  output: true

# Details for the RSS feed generator
url:            'http://yuriysteam.github.io'
author:         'Yuriy Shiryaev'
twitter: 'yuriysteam'